--THERE ARE TWO POINTS IN A TRANSACTION

--BEGIN POINT

--END IN TWO WAYS
--COMMIT / ROLLBACK POINT


--SQL SERVER BY DEFAULT USES AUTOCOMMIT MODE

--DML

--EXAMPLE SINGLE TASK TRANSACTION

UPDATE Customer
SET MobileNo = '9837952830'
WHERE CustomerId = 1

--THIS TRANSACTION HAS EXECUTED ON AN AUTOCOMMIT MODE (DEFAULT MODE IN SQL SERVER)


SELECT * FROM Customer 


--EXPLICIT (MANUALLY) HANDLING THE TRANSACTIONS

BEGIN TRANSACTION t1
   UPDATE Customer
   SET MobileNo = '9837952832'
   WHERE CustomerId = 1
--COMMIT means that the transaction has been recorded to the log file
COMMIT TRANSACTION t1


ROLLBACK TRANSACTION t1


select * from Customer 